export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
